### ISSUE TITLE
创建一个用户，登陆后退出，重新登陆，无法登陆，数据库有一条用户记录

### ISSUE THREAD

**Issue by MRchao90s** [thx/rap2-delos#570]
**BUG描述**
在使用官方文档生成docker镜像进行部署，发现无法登陆
使用注册用户可以正常进去并且操作
**复现步骤**
创建一个用户，登陆后退出，重新登陆，无法登陆，数据库有一条用户记录，后端docker logs 无报错

**期望结果**
可以登陆进去

**实际结果**
提示账号或密码错误

**截图**
![image](https://user-images.githubusercontent.com/25077986/65700080-a09d3000-e0b1-11e9-8ce3-3cd75ddcb8c8.png)
![image](https://user-images.githubusercontent.com/25077986/65700118-b01c7900-e0b1-11e9-97b9-adc9b31f2584.png)

**环境**
* centos 7  docker 镜像
* 浏览器 chorme 70
* 其它可能帮助我们排查问题的环境信息
生成的镜像用的都是最近的代码 2019年9月26日 23:07:36 取的代码  

**附加信息**

```yml
# mail@dongguochao.com
version: '2.2'
services:
  delos:
    container_name: rap2-delos
    # build from ./Dockerfile
    #    build: .
    # build from images
    image: ccgao/rap2-delos:2.6.csoft
    environment:
      # if you have your own mysql, config it here, and disable the 'mysql' config blow
      - MYSQL_URL=rap2-mysql # links will maintain /etc/hosts, just use 'container_name'
      - MYSQL_PORT=3306
      - MYSQL_USERNAME=root
      - MYSQL_PASSWD=
      - MYSQL_SCHEMA=rap2
      # redis config
      - REDIS_URL=rap2-redis
      - REDIS_PORT=6379
      # production / development
      - NODE_ENV=production
    working_dir: /app
    privileged: true
    ###### 'sleep 30 && node scripts/init' will drop the tables
    ###### RUN ONLY ONCE THEN REMOVE 'sleep 30 && node scripts/init'
    command: /bin/sh -c 'sleep 30; node scripts/init; node dispatch.js'
    # init the databases
    #    command: sleep 30 && node scripts/init && node dispatch.js
    # without init
    #    command: node dispatch.js
    links:
      - redis
      - mysql
    depends_on:
      - redis
      - mysql
    ports:
      - "38080:8084"  # expose 38080
  redis:
    container_name: rap2-redis
    image: redis:4.0.9
  # disable this if you have your own mysql
  mysql:
    container_name: rap2-mysql
    image: mysql:5.7.22
    # expose 33306 to client (navicat)
    #ports:
    #   - 33306:3306
    volumes:
      # change './docker/mysql/volume' to your own path
      # WARNING: without this line, your data will be lost.
      - "/mnt/disk2/cc.gao/data/mysql/volume:/var/lib/mysql"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-connect='SET NAMES utf8mb4;' --innodb-flush-log-at-trx-commit=0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: "rap2"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: ""
```

add on 2019年9月26日 23:34:16

启动外网测试和内网测试，centos本地mysql 本地redis 测试新增账号登陆不通过
![image](https://user-images.githubusercontent.com/25077986/65702913-68e4b700-e0b6-11e9-8097-e93fc3c1a2b2.png)
